baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
relativeUrls = true
#title = "Website of Vikas Negi"

# Theme as git submodule
theme = "anatole"

# Left pane
[params]
title = "Vikas Negi"
author = "Vikas Negi"
description = "Hello, welcome to my personal site powered by Web 3.0!"
profilePicture = "VNEG_pic.jpg"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

# Social media icons
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/vnegi10"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/negivikas/"

[[params.socialIcons]]
icon = "fab fa-medium"
title = "Medium"
url = "https://medium.com/@vikas.negi10"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:vikas.negi10@gmail.com"

# Menus on the right pane
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/home/"

  [[menu.main]]
  name = "CV"
  identifier = "CV"
  weight = 100
  url = "/cv/"

  [[menu.main]]
  name = "Blogs"
  weight = 200
  identifier = "blogs"
  url = "/blogs/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Resources"
  weight = 500
  identifier = "resources"
  url = "/resources/"